<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (FUN_CODE?,FUN_NAME?,FUN_TYPE?,FUN_DESC?)+>
  <!ELEMENT FUN_CODE (#PCDATA)>
  <!ELEMENT FUN_NAME (#PCDATA)>
  <!ELEMENT FUN_TYPE (#PCDATA)>
  <!ELEMENT FUN_DESC (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <FUN_CODE>0100000000</FUN_CODE>
    <FUN_NAME>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;</FUN_NAME>
    <FUN_TYPE>S</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101000000</FUN_CODE>
    <FUN_NAME>&#20316;&#26989;&#35373;&#23450;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#20316;&#26989;&#35373;&#23450;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101010000</FUN_CODE>
    <FUN_NAME>&#35330;&#36008;&#20844;&#24335;&#35373;&#23450;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#35330;&#36008;&#20844;&#24335;&#35373;&#23450;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101010001</FUN_CODE>
    <FUN_NAME>&#35330;&#36008;&#31649;&#29702;&#21729;</FUN_NAME>
    <FUN_TYPE>R</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#31649;&#29702;&#21729;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101010002</FUN_CODE>
    <FUN_NAME>&#19968;&#33324;&#35330;&#36008;&#21729;</FUN_NAME>
    <FUN_TYPE>R</FUN_TYPE>
    <FUN_DESC>&#19968;&#33324;&#35330;&#36008;&#21729;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101010003</FUN_CODE>
    <FUN_NAME>&#35330;&#36008;&#26597;&#35426;&#21729;</FUN_NAME>
    <FUN_TYPE>R</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#26597;&#35426;&#21729;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101010100</FUN_CODE>
    <FUN_NAME>&#35330;&#36008;&#20844;&#24335;&#35373;&#23450;-&#26032;&#22686;</FUN_NAME>
    <FUN_TYPE>R</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20844;&#24335;&#35373;&#23450;-&#26032;&#22686;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101010200</FUN_CODE>
    <FUN_NAME>&#35330;&#36008;&#20844;&#24335;&#35373;&#23450;-&#20462;&#25913;</FUN_NAME>
    <FUN_TYPE>R</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20844;&#24335;&#35373;&#23450;-&#20462;&#25913;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101010300</FUN_CODE>
    <FUN_NAME>&#35330;&#36008;&#20844;&#24335;&#35373;&#23450;-&#21034;&#38500;</FUN_NAME>
    <FUN_TYPE>R</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20844;&#24335;&#35373;&#23450;-&#21034;&#38500;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101020000</FUN_CODE>
    <FUN_NAME>&#36914;&#36008;&#30446;&#27161;&#35373;&#23450;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#36914;&#36008;&#30446;&#27161;&#35373;&#23450;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101030000</FUN_CODE>
    <FUN_NAME>&#21830;&#21697;&#20379;&#36008;&#22320;&#40670;&#35373;&#23450;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#21830;&#21697;&#20379;&#36008;&#22320;&#40670;&#35373;&#23450;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101040000</FUN_CODE>
    <FUN_NAME>&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101050000</FUN_CODE>
    <FUN_NAME>&#19981;&#32624;&#27454;&#24288;&#21830;&#35373;&#23450;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#19981;&#32624;&#27454;&#24288;&#21830;&#35373;&#23450;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101060000</FUN_CODE>
    <FUN_NAME>&#24288;&#21830;&#20379;&#36008;&#22320;&#40670;&#32173;&#35703;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#24288;&#21830;&#20379;&#36008;&#22320;&#40670;&#32173;&#35703;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101070000</FUN_CODE>
    <FUN_NAME>&#24180;&#32066;&#21507;&#36008;&#36914;&#36008;&#30446;&#27161;&#34389;&#29702;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#24180;&#32066;&#21507;&#36008;&#36914;&#36008;&#30446;&#27161;&#34389;&#29702;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101080000</FUN_CODE>
    <FUN_NAME>&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;&#32173;&#35703;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;&#32173;&#35703;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101080100</FUN_CODE>
    <FUN_NAME>&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;&#32173;&#35703;-&#26032;&#22686;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;&#32173;&#35703;-&#26032;&#22686;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101080200</FUN_CODE>
    <FUN_NAME>&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;&#32173;&#35703;-&#20462;&#25913;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;&#32173;&#35703;-&#20462;&#25913;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0101080300</FUN_CODE>
    <FUN_NAME>&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;&#32173;&#35703;-&#21034;&#38500;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21015;&#31649;&#21830;&#21697;&#35373;&#23450;&#32173;&#35703;-&#21034;&#38500;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102000000</FUN_CODE>
    <FUN_NAME>&#35330;&#36008;&#20316;&#26989;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#35330;&#36008;&#20316;&#26989;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102010000</FUN_CODE>
    <FUN_NAME>&#35330;&#36008;&#24314;&#35696;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#35330;&#36008;&#24314;&#35696;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102020000</FUN_CODE>
    <FUN_NAME>&#19968;&#33324;&#35330;&#36008;&#20316;&#26989;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#19968;&#33324;&#35330;&#36008;&#20316;&#26989;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102030000</FUN_CODE>
    <FUN_NAME>&#25552;&#21069;&#35330;&#36008;&#20316;&#26989;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#25552;&#21069;&#35330;&#36008;&#20316;&#26989;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102040000</FUN_CODE>
    <FUN_NAME>&#38928;&#35686;&#20316;&#26989;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#38928;&#35686;&#20316;&#26989;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102050000</FUN_CODE>
    <FUN_NAME>&#24314;&#35696;&#25976;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>P</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#24314;&#35696;&#25976;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102060000</FUN_CODE>
    <FUN_NAME>&#24288;&#21830;&#21029;&#21830;&#21697;&#35330;&#36008;&#32000;&#37636;&#34920;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#24288;&#21830;&#21029;&#21830;&#21697;&#35330;&#36008;&#32000;&#37636;&#34920;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102070000</FUN_CODE>
    <FUN_NAME>&#35330;&#21934;&#32173;&#35703;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#35330;&#21934;&#32173;&#35703;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102080000</FUN_CODE>
    <FUN_NAME>&#29986;&#29983;&#35330;&#21934;&#25991;&#23383;&#27284;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#29986;&#29983;&#35330;&#21934;&#25991;&#23383;&#27284;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102090000</FUN_CODE>
    <FUN_NAME>&#21015;&#21360;&#38928;&#35686;&#22577;&#34920;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;-&#21015;&#21360;&#38928;&#35686;&#22577;&#34920;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0102130000</FUN_CODE>
    <FUN_NAME>NEOS&#36681;&#24288;&#35330;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;NEOS&#36681;&#24288;&#35330;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103000000</FUN_CODE>
    <FUN_NAME>&#21040;&#36008;&#32624;&#27454;&#31649;&#29702;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#21040;&#36008;&#32624;&#27454;&#31649;&#29702;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103010000</FUN_CODE>
    <FUN_NAME>&#21040;&#36008;&#32624;&#27454;&#34389;&#29702;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#21040;&#36008;&#32624;&#27454;&#34389;&#29702;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020000</FUN_CODE>
    <FUN_NAME>&#21040;&#36008;&#32624;&#27454;&#20998;&#26512;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#21040;&#36008;&#32624;&#27454;&#20998;&#26512;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020100</FUN_CODE>
    <FUN_NAME>&#27599;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27599;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020200</FUN_CODE>
    <FUN_NAME>&#27599;&#26085;&#21040;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27599;&#26085;&#21040;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020300</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020400</FUN_CODE>
    <FUN_NAME>&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020500</FUN_CODE>
    <FUN_NAME>&#26412;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26412;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020600</FUN_CODE>
    <FUN_NAME>&#21040;&#36008;&#32624;&#27454;&#25104;&#31435;&#36890;&#30693;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21040;&#36008;&#32624;&#27454;&#25104;&#31435;&#36890;&#30693;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020700</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#25490;&#34892;&#27036;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#25490;&#34892;&#27036;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020800</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#29575;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#29575;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103020900</FUN_CODE>
    <FUN_NAME>&#21407;&#22987;&#36039;&#26009;&#36681;&#25104;&#20998;&#26512;&#27284;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21407;&#22987;&#36039;&#26009;&#36681;&#25104;&#20998;&#26512;&#27284;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030000</FUN_CODE>
    <FUN_NAME>&#21040;&#36008;&#32624;&#27454;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>P</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#21040;&#36008;&#32624;&#27454;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030100</FUN_CODE>
    <FUN_NAME>&#27599;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27599;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030200</FUN_CODE>
    <FUN_NAME>&#27599;&#26085;&#21040;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27599;&#26085;&#21040;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030300</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030400</FUN_CODE>
    <FUN_NAME>&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030500</FUN_CODE>
    <FUN_NAME>&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#26126;&#32048;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#26126;&#32048;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030600</FUN_CODE>
    <FUN_NAME>&#26412;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26412;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030700</FUN_CODE>
    <FUN_NAME>&#26412;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#26126;&#32048;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26412;&#26085;&#21040;&#36008;&#30064;&#24120;&#24288;&#21830;&#26126;&#32048;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030800</FUN_CODE>
    <FUN_NAME>&#21040;&#36008;&#32624;&#27454;&#25104;&#31435;&#36890;&#30693;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21040;&#36008;&#32624;&#27454;&#25104;&#31435;&#36890;&#30693;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103030900</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#25490;&#34892;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#25490;&#34892;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103031000</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#29575;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#21040;&#36008;&#30064;&#24120;&#29575;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0103040000</FUN_CODE>
    <FUN_NAME>&#24288;&#21830;&#24310;&#36978;&#26410;&#21040;&#36008;&#32080;&#21934;&#32173;&#35703;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#24288;&#21830;&#24310;&#36978;&#26410;&#21040;&#36008;&#32080;&#21934;&#32173;&#35703;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104000000</FUN_CODE>
    <FUN_NAME>&#38272;&#24066;&#32570;&#36008;&#34389;&#29702;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#38272;&#24066;&#32570;&#36008;&#34389;&#29702;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104010000</FUN_CODE>
    <FUN_NAME>&#38272;&#24066;&#32570;&#36008;&#34389;&#29702;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#38272;&#24066;&#32570;&#36008;&#34389;&#29702;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020000</FUN_CODE>
    <FUN_NAME>&#38272;&#24066;&#32570;&#36008;&#20998;&#26512;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#38272;&#24066;&#32570;&#36008;&#20998;&#26512;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020100</FUN_CODE>
    <FUN_NAME>&#27599;&#26085;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27599;&#26085;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020200</FUN_CODE>
    <FUN_NAME>&#27599;&#26085;&#20986;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27599;&#26085;&#20986;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020300</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020400</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020500</FUN_CODE>
    <FUN_NAME>&#21934;&#21697;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21934;&#21697;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020600</FUN_CODE>
    <FUN_NAME>&#38272;&#24066;&#32570;&#36008;&#25104;&#31435;&#36890;&#30693;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#38272;&#24066;&#32570;&#36008;&#25104;&#31435;&#36890;&#30693;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020700</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#25490;&#34892;&#27036;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#25490;&#34892;&#27036;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020800</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#29575;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#29575;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104020900</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#21830;&#21697;&#32570;&#36008;&#24409;&#32317;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#21830;&#21697;&#32570;&#36008;&#24409;&#32317;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104021100</FUN_CODE>
    <FUN_NAME>&#21407;&#22987;&#36039;&#26009;&#36681;&#25104;&#20998;&#26512;&#27284;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21407;&#22987;&#36039;&#26009;&#36681;&#25104;&#20998;&#26512;&#27284;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030000</FUN_CODE>
    <FUN_NAME>&#38272;&#24066;&#32570;&#36008;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>P</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#38272;&#24066;&#32570;&#36008;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030100</FUN_CODE>
    <FUN_NAME>&#27599;&#26085;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27599;&#26085;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030200</FUN_CODE>
    <FUN_NAME>&#27599;&#26085;&#20986;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27599;&#26085;&#20986;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030300</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#21407;&#22240;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030400</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030500</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#26126;&#32048;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#26126;&#32048;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030600</FUN_CODE>
    <FUN_NAME>&#21934;&#21697;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21934;&#21697;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030700</FUN_CODE>
    <FUN_NAME>&#21934;&#21697;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#26126;&#32048;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21934;&#21697;&#20986;&#36008;&#30064;&#24120;&#38272;&#24066;&#26126;&#32048;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030800</FUN_CODE>
    <FUN_NAME>&#38272;&#24066;&#32570;&#36008;&#25104;&#31435;&#36890;&#30693;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#38272;&#24066;&#32570;&#36008;&#25104;&#31435;&#36890;&#30693;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104030900</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#25490;&#34892;&#27036;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#25490;&#34892;&#27036;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104031000</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#29575;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#20986;&#36008;&#30064;&#24120;&#29575;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104031100</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#21830;&#21697;&#32570;&#36008;&#24409;&#32317;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#21830;&#21697;&#32570;&#36008;&#24409;&#32317;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0104031200</FUN_CODE>
    <FUN_NAME>&#26399;&#38291;&#21830;&#21697;&#32570;&#36008;&#26126;&#32048;&#21015;&#21360;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#26399;&#38291;&#21830;&#21697;&#32570;&#36008;&#26126;&#32048;&#21015;&#21360;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105000000</FUN_CODE>
    <FUN_NAME>&#36914;&#20986;&#36008;&#20998;&#26512;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#36914;&#20986;&#36008;&#20998;&#26512;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105010000</FUN_CODE>
    <FUN_NAME>&#24288;&#21830;&#22522;&#26412;&#36039;&#26009;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#24288;&#21830;&#22522;&#26412;&#36039;&#26009;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105020000</FUN_CODE>
    <FUN_NAME>&#26032;&#21697;&#65311;&#20419;&#37559;&#21697;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#26032;&#21697;&#65311;&#20419;&#37559;&#21697;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105030000</FUN_CODE>
    <FUN_NAME>&#20572;&#21806;&#65311;&#24288;&#32570;&#65311;&#20241;&#37197;&#26597;&#35426;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#20572;&#21806;&#65311;&#24288;&#32570;&#65311;&#20241;&#37197;&#26597;&#35426;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105040000</FUN_CODE>
    <FUN_NAME>&#35330;&#21934;&#26597;&#35426;&#40;&#21934;&#21697;&#65311;&#24288;&#21830;&#41;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#35330;&#21934;&#26597;&#35426;&#40;&#21934;&#21697;&#65311;&#24288;&#21830;&#41;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105050000</FUN_CODE>
    <FUN_NAME>DC&#21830;&#21697;&#36914;&#20986;&#20998;&#26512;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;DC&#21830;&#21697;&#36914;&#20986;&#20998;&#26512;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105060000</FUN_CODE>
    <FUN_NAME>&#24288;&#21830;&#21830;&#21697;&#36914;&#20986;&#20998;&#26512;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#24288;&#21830;&#21830;&#21697;&#36914;&#20986;&#20998;&#26512;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105070000</FUN_CODE>
    <FUN_NAME>&#38272;&#24066;&#21830;&#21697;&#36914;&#20986;&#20998;&#26512;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#38272;&#24066;&#21830;&#21697;&#36914;&#20986;&#20998;&#26512;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105080000</FUN_CODE>
    <FUN_NAME>&#27511;&#21490;&#21830;&#21697;&#36914;&#20986;&#20998;&#26512;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#35330;&#36008;&#20316;&#26989;&#31995;&#32113;&#9472;&#27511;&#21490;&#21830;&#21697;&#36914;&#20986;&#20998;&#26512;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105080100</FUN_CODE>
    <FUN_NAME>&#21830;&#21697;&#37559;&#21806;&#26376;&#22577;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21830;&#21697;&#37559;&#21806;&#26376;&#22577;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105080200</FUN_CODE>
    <FUN_NAME>&#21830;&#21697;ABC&#20998;&#26512;&#24409;&#32317;&#65311;&#26126;&#32048;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#21830;&#21697;ABC&#20998;&#26512;&#24409;&#32317;&#65311;&#26126;&#32048;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105080300</FUN_CODE>
    <FUN_NAME>&#27511;&#21490;&#21830;&#21697;&#36914;&#20986;&#36039;&#26009;&#24409;&#32317;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27511;&#21490;&#21830;&#21697;&#36914;&#20986;&#36039;&#26009;&#24409;&#32317;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105080400</FUN_CODE>
    <FUN_NAME>&#27511;&#21490;&#21830;&#21697;&#36914;&#20986;&#36039;&#26009;&#26126;&#32048;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#27511;&#21490;&#21830;&#21697;&#36914;&#20986;&#36039;&#26009;&#26126;&#32048;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0105090000</FUN_CODE>
    <FUN_NAME>&#24235;&#23384;&#20729;&#24046;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>
    <FUN_DESC>&#24235;&#23384;&#20729;&#24046;</FUN_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <FUN_CODE>0106000000</FUN_CODE>
    <FUN_NAME>&#35338;&#24687;&#31649;&#29702;</FUN_NAME>
    <FUN_TYPE>F</FUN_TYPE>